# Generated by Django 4.2.7 on 2023-12-05 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='colour',
            field=models.CharField(blank=True, choices=[('blue', 'Синий'), ('green', 'Зеленый')], max_length=50, null=True, verbose_name='Цвет статуса'),
        ),
    ]
