# Generated by Django 4.2.7 on 2023-12-08 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_colour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='articul',
        ),
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='old_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
    ]
