# Generated by Django 4.2.7 on 2023-12-26 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_product_service_product_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(upload_to='products_photo/', verbose_name='Фото товара'),
        ),
    ]
