version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    restart: always
    environment:
      - TZ=${TIME_ZONE}
    env_file:
      - .env
    volumes:
      - static_volume:/app/static/
      - media_volume:/app/media/

  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "15432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data/

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"

  nginx:
    build:
      context: .
      dockerfile: stroyinvest/deploy/Dockerfile.nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - static_volume:/app/static/
      - media_volume:/app/media/
    depends_on:
      - web

volumes:
  pg_data:
  static_volume:
  media_volume:
