version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    restart: always
    env_file:
      - .env
    volumes:
      - static_volume:/app/static/
      - ./stroyinvest/media_volume:/app/media/

  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./stroyinvest/pg_data:/var/lib/postgresql/data/

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: [ "redis-server", "--appendonly", "yes", "--slave-serve-stale-data", "no" ]

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A stroyinvest worker -l info
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
      - web

  nginx:
    build:
      context: .
      dockerfile: stroyinvest/deploy/Dockerfile.nginx
    command: nginx -g 'daemon off;'
    restart: always
    volumes:
      - static_volume:/app/static/
      - ./stroyinvest/media_volume:/app/media/
    depends_on:
      - web

  nginx_proxy_pass:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./stroyinvest/nginx_data:/data
      - ./stroyinvest/letsencrypt_data:/etc/letsencrypt


volumes:
  pg_data:
  static_volume:
  media_volume:
  redis_data:
  nginx_data:
  letsencrypt_data: