version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    environment:
      - TZ=Asia/Vladivostok
    env_file:
      - .env

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=stroyinvest
      - POSTGRES_USER=stroyinvest
      - POSTGRES_PASSWORD=stroyinvest
    ports:
      - "15432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data/

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  nginx:
    build:
      context: .
      dockerfile: ./stroyinvest/nginx/Dockerfile.nginx
    restart: always
    volumes:
      - static_volume:/app/static/
      - media_volume:/app/media/
    depends_on:
      - web

  nginx_proxy_pass:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - nginx_data:/data
      - letsencrypt_data:/etc/letsencrypt


volumes:
  pg_data:
  static_volume:
  media_volume:
  nginx_data:
  letsencrypt_data: