# Generated by Django 4.2.7 on 2023-12-26 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_service_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='photo',
            field=models.ImageField(upload_to='service_photo', verbose_name='Фото услуги'),
        ),
    ]
