# Generated by Django 4.2.7 on 2023-12-04 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_icon_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icon',
            name='icon',
            field=models.TextField(verbose_name='Иконка услуги'),
        ),
    ]
