FROM nginx:1.21

RUN rm /etc/nginx/conf.d/default.conf

RUN mkdir -p /etc/nginx/conf.d

COPY /stroyinvest/deploy/nginx.conf /etc/nginx/conf.d/default.conf

COPY ./stroyinvest/static /app/static